language: node_js
node_js:
  - "6.11.2"
env:
  - CXX=g++-4.8
script:
  - npm install
  - npm run build:dll
  - npm run build
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
